project:
  type: website
  output-dir: _site
  resources: 
    - "!README.md"

website:
  title: Detecting Anomalies in Credit Card Transactions
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO-523-SU25/final-project-Rodriguez
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true

execute:
  freeze: auto
